BEGIN;
-- Negative user knowledge is distinct from matching results and source availability.
CREATE TABLE track_provider_exclusion (
 track_id TEXT NOT NULL REFERENCES track(id) ON DELETE CASCADE,
 provider TEXT NOT NULL,
 declared_at INTEGER NOT NULL DEFAULT(unixepoch()),
 PRIMARY KEY(track_id,provider)
) STRICT;
CREATE INDEX provider_exclusion_list ON track_provider_exclusion(provider,track_id);
ALTER TABLE spotify_connection_review ADD COLUMN evaluation_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spotify_connection_review ADD COLUMN stale INTEGER NOT NULL DEFAULT 1 CHECK(stale IN(0,1));
ALTER TABLE spotify_connection_review ADD COLUMN state TEXT NOT NULL DEFAULT 'unresolved' CHECK(state IN('unresolved','needs_retry'));
CREATE INDEX spotify_review_stale ON spotify_connection_review(stale,track_id);
CREATE INDEX spotify_review_version ON spotify_connection_review(evaluation_version,track_id);
CREATE TABLE spotify_reconciliation_cache (
 track_id TEXT PRIMARY KEY REFERENCES track(id) ON DELETE CASCADE,
 input_json TEXT NOT NULL CHECK(json_valid(input_json)),
 page_json TEXT NOT NULL CHECK(json_valid(page_json))
) STRICT;
CREATE TABLE spotify_program_cache (
 album_id TEXT PRIMARY KEY REFERENCES album(id) ON DELETE CASCADE,
 programs_json TEXT NOT NULL CHECK(json_valid(programs_json))
) STRICT;
CREATE TRIGGER spotify_exclusion_unconnected BEFORE INSERT ON track_provider_exclusion
WHEN NEW.provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id)
BEGIN SELECT RAISE(ABORT,'Connected Track cannot be marked not on Spotify'); END;
CREATE TRIGGER lifecycle_track_provider_evidence_insert AFTER INSERT ON track_provider_evidence BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_provider_evidence_update AFTER UPDATE ON track_provider_evidence WHEN NEW.track_id IS NOT OLD.track_id OR NEW.provider IS NOT OLD.provider OR NEW.kind IS NOT OLD.kind OR NEW.external_id IS NOT OLD.external_id OR NEW.title IS NOT OLD.title OR NEW.disc IS NOT OLD.disc OR NEW.position IS NOT OLD.position OR NEW.duration_ms IS NOT OLD.duration_ms BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_provider_evidence_delete AFTER DELETE ON track_provider_evidence BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_application_metadata_insert AFTER INSERT ON track_application_metadata BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_application_metadata_update AFTER UPDATE ON track_application_metadata WHEN NEW.track_id IS NOT OLD.track_id OR NEW.title IS NOT OLD.title BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_application_metadata_delete AFTER DELETE ON track_application_metadata BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_title_override_insert AFTER INSERT ON track_title_override BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_title_override_update AFTER UPDATE ON track_title_override WHEN NEW.track_id IS NOT OLD.track_id OR NEW.value IS NOT OLD.value OR NEW.updated_at IS NOT OLD.updated_at BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_title_override_delete AFTER DELETE ON track_title_override BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_external_identity_insert AFTER INSERT ON track_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_external_identity_update AFTER UPDATE ON track_external_identity WHEN NEW.track_id IS NOT OLD.track_id OR NEW.provider IS NOT OLD.provider OR NEW.kind IS NOT OLD.kind OR NEW.external_id IS NOT OLD.external_id BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_external_identity_delete AFTER DELETE ON track_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_artist_credit_insert AFTER INSERT ON track_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_artist_credit_update AFTER UPDATE ON track_artist_credit WHEN NEW.track_id IS NOT OLD.track_id OR NEW.position IS NOT OLD.position OR NEW.artist_id IS NOT OLD.artist_id OR NEW.role IS NOT OLD.role OR NEW.join_phrase IS NOT OLD.join_phrase OR NEW.credited_name IS NOT OLD.credited_name BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_artist_credit_delete AFTER DELETE ON track_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_duration_observation_insert AFTER INSERT ON track_duration_observation BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_duration_observation_update AFTER UPDATE ON track_duration_observation WHEN NEW.track_id IS NOT OLD.track_id OR NEW.provider IS NOT OLD.provider OR NEW.source_key IS NOT OLD.source_key OR NEW.duration_ms IS NOT OLD.duration_ms OR NEW.quality IS NOT OLD.quality BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_duration_observation_delete AFTER DELETE ON track_duration_observation BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_source_insert AFTER INSERT ON track_source BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_source_update AFTER UPDATE ON track_source WHEN NEW.track_id IS NOT OLD.track_id OR NEW.source_id IS NOT OLD.source_id BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=NEW.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_source_delete AFTER DELETE ON track_source BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.id=OLD.track_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_provider_evidence_insert AFTER INSERT ON album_provider_evidence BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_provider_evidence_update AFTER UPDATE ON album_provider_evidence WHEN NEW.album_id IS NOT OLD.album_id OR NEW.provider IS NOT OLD.provider OR NEW.kind IS NOT OLD.kind OR NEW.external_id IS NOT OLD.external_id OR NEW.title IS NOT OLD.title OR NEW.release_date IS NOT OLD.release_date OR NEW.release_type IS NOT OLD.release_type BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_provider_evidence_delete AFTER DELETE ON album_provider_evidence BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_application_metadata_insert AFTER INSERT ON album_application_metadata BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_application_metadata_update AFTER UPDATE ON album_application_metadata WHEN NEW.album_id IS NOT OLD.album_id OR NEW.title IS NOT OLD.title OR NEW.year IS NOT OLD.year OR NEW.match_title IS NOT OLD.match_title OR NEW.match_artist_credit IS NOT OLD.match_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_application_metadata_delete AFTER DELETE ON album_application_metadata BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_external_identity_insert AFTER INSERT ON album_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_external_identity_update AFTER UPDATE ON album_external_identity WHEN NEW.album_id IS NOT OLD.album_id OR NEW.provider IS NOT OLD.provider OR NEW.kind IS NOT OLD.kind OR NEW.external_id IS NOT OLD.external_id BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_external_identity_delete AFTER DELETE ON album_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_artist_credit_insert AFTER INSERT ON album_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_artist_credit_update AFTER UPDATE ON album_artist_credit WHEN NEW.album_id IS NOT OLD.album_id OR NEW.position IS NOT OLD.position OR NEW.artist_id IS NOT OLD.artist_id OR NEW.role IS NOT OLD.role OR NEW.join_phrase IS NOT OLD.join_phrase OR NEW.credited_name IS NOT OLD.credited_name BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_album_artist_credit_delete AFTER DELETE ON album_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=OLD.album_id) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_external_identity_insert AFTER INSERT ON release_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=NEW.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_external_identity_update AFTER UPDATE ON release_external_identity WHEN NEW.release_id IS NOT OLD.release_id OR NEW.provider IS NOT OLD.provider OR NEW.kind IS NOT OLD.kind OR NEW.external_id IS NOT OLD.external_id BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=OLD.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=NEW.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_external_identity_delete AFTER DELETE ON release_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=OLD.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_artist_credit_insert AFTER INSERT ON release_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=NEW.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_artist_credit_update AFTER UPDATE ON release_artist_credit WHEN NEW.release_id IS NOT OLD.release_id OR NEW.position IS NOT OLD.position OR NEW.artist_id IS NOT OLD.artist_id OR NEW.role IS NOT OLD.role OR NEW.join_phrase IS NOT OLD.join_phrase OR NEW.credited_name IS NOT OLD.credited_name BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=OLD.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=NEW.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_artist_credit_delete AFTER DELETE ON release_artist_credit BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=OLD.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_file_metadata_observation_insert AFTER INSERT ON file_metadata_observation BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=NEW.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_file_metadata_observation_update AFTER UPDATE ON file_metadata_observation WHEN NEW.source_id IS NOT OLD.source_id OR NEW.track_title IS NOT OLD.track_title OR NEW.release_title IS NOT OLD.release_title OR NEW.disc_number IS NOT OLD.disc_number OR NEW.track_number IS NOT OLD.track_number OR NEW.year IS NOT OLD.year OR NEW.duration_ms IS NOT OLD.duration_ms OR NEW.format IS NOT OLD.format OR NEW.provenance_json IS NOT OLD.provenance_json OR NEW.genres_observed IS NOT OLD.genres_observed BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=OLD.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=NEW.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_file_metadata_observation_delete AFTER DELETE ON file_metadata_observation BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=OLD.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_file_artist_observation_insert AFTER INSERT ON file_artist_observation BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=NEW.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_file_artist_observation_update AFTER UPDATE ON file_artist_observation WHEN NEW.source_id IS NOT OLD.source_id OR NEW.scope IS NOT OLD.scope OR NEW.position IS NOT OLD.position OR NEW.name IS NOT OLD.name BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=OLD.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=NEW.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_file_artist_observation_delete AFTER DELETE ON file_artist_observation BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track_source ts JOIN track t2 ON t2.id=ts.track_id JOIN release r2 ON r2.id=t2.release_id WHERE ts.source_id=OLD.source_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_insert AFTER INSERT ON artist BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT NEW.id UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_update AFTER UPDATE ON artist WHEN NEW.id IS NOT OLD.id OR NEW.name IS NOT OLD.name BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT OLD.id UNION SELECT NEW.id UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_delete AFTER DELETE ON artist BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT OLD.id UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_external_identity_insert AFTER INSERT ON artist_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT NEW.artist_id UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_external_identity_update AFTER UPDATE ON artist_external_identity WHEN NEW.artist_id IS NOT OLD.artist_id OR NEW.provider IS NOT OLD.provider OR NEW.kind IS NOT OLD.kind OR NEW.external_id IS NOT OLD.external_id BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT OLD.artist_id UNION SELECT NEW.artist_id UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_external_identity_delete AFTER DELETE ON artist_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT OLD.artist_id UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_equivalence_insert AFTER INSERT ON artist_equivalence BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT NEW.artist_a UNION SELECT NEW.artist_b UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_equivalence_update AFTER UPDATE ON artist_equivalence WHEN NEW.artist_a IS NOT OLD.artist_a OR NEW.artist_b IS NOT OLD.artist_b BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT OLD.artist_a UNION SELECT OLD.artist_b UNION SELECT NEW.artist_a UNION SELECT NEW.artist_b UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_artist_equivalence_delete AFTER DELETE ON artist_equivalence BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(WITH RECURSIVE linked(id) AS (SELECT OLD.artist_a UNION SELECT OLD.artist_b UNION SELECT CASE WHEN e.artist_a=l.id THEN e.artist_b ELSE e.artist_a END FROM linked l JOIN artist_equivalence e ON e.artist_a=l.id OR e.artist_b=l.id) SELECT c.track_id FROM track_artist_credit c WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM release_artist_credit c JOIN track t ON t.release_id=c.release_id WHERE c.artist_id IN(SELECT id FROM linked) UNION SELECT t.id FROM album_artist_credit c JOIN release r ON r.album_id=c.album_id JOIN track t ON t.release_id=r.id WHERE c.artist_id IN(SELECT id FROM linked)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_insert AFTER INSERT ON track BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=NEW.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_update AFTER UPDATE ON track WHEN NEW.id IS NOT OLD.id OR NEW.release_id IS NOT OLD.release_id OR NEW.recording_id IS NOT OLD.recording_id OR NEW.disc_number IS NOT OLD.disc_number OR NEW.track_number IS NOT OLD.track_number BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=OLD.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=NEW.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_track_delete AFTER DELETE ON track BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT album_id FROM release WHERE id=OLD.release_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_release_relationship AFTER UPDATE OF album_id ON release BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(OLD.album_id,NEW.album_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_connected_track_external_identity_insert AFTER INSERT ON track_external_identity WHEN NEW.provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id) BEGIN DELETE FROM track_provider_exclusion WHERE track_id=NEW.track_id AND provider='spotify'; UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id; END;
CREATE TRIGGER lifecycle_connected_track_external_identity_update AFTER UPDATE ON track_external_identity WHEN NEW.provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id) BEGIN DELETE FROM track_provider_exclusion WHERE track_id=NEW.track_id AND provider='spotify'; UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id; END;
CREATE TRIGGER lifecycle_connected_manual_track_association_insert AFTER INSERT ON manual_track_association WHEN NEW.album_provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id) BEGIN DELETE FROM track_provider_exclusion WHERE track_id=NEW.track_id AND provider='spotify'; UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id; END;
CREATE TRIGGER lifecycle_connected_manual_track_association_update AFTER UPDATE ON manual_track_association WHEN NEW.album_provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id) BEGIN DELETE FROM track_provider_exclusion WHERE track_id=NEW.track_id AND provider='spotify'; UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id; END;
CREATE TRIGGER lifecycle_connected_provider_track_association_insert AFTER INSERT ON provider_track_association WHEN NEW.album_provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id) BEGIN DELETE FROM track_provider_exclusion WHERE track_id=NEW.track_id AND provider='spotify'; UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id; END;
CREATE TRIGGER lifecycle_connected_provider_track_association_update AFTER UPDATE ON provider_track_association WHEN NEW.album_provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id) BEGIN DELETE FROM track_provider_exclusion WHERE track_id=NEW.track_id AND provider='spotify'; UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id; END;
-- Existing successful associations need no upgrade work; only review bookkeeping changes.
UPDATE spotify_connection_review SET evaluation_version=2,stale=0 WHERE EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id);
CREATE TRIGGER spotify_exclusion_update_unconnected BEFORE UPDATE ON track_provider_exclusion
WHEN NEW.provider='spotify' AND EXISTS(SELECT 1 FROM trusted_spotify_track WHERE track_id=NEW.track_id)
BEGIN SELECT RAISE(ABORT,'Connected Track cannot be marked not on Spotify'); END;
CREATE TRIGGER lifecycle_exclusion_added AFTER INSERT ON track_provider_exclusion WHEN NEW.provider='spotify' BEGIN
 UPDATE spotify_connection_review SET stale=0,evaluation_version=2 WHERE track_id=NEW.track_id;
END;
CREATE TRIGGER lifecycle_exclusion_removed AFTER DELETE ON track_provider_exclusion WHEN OLD.provider='spotify' BEGIN
 UPDATE spotify_connection_review SET stale=1 WHERE track_id=OLD.track_id;
END;
CREATE TRIGGER lifecycle_album_identity_connected_insert AFTER INSERT ON album_external_identity WHEN NEW.provider='spotify' BEGIN
 DELETE FROM track_provider_exclusion WHERE provider='spotify' AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=track_provider_exclusion.track_id);
END;
CREATE TRIGGER lifecycle_album_identity_connected_update AFTER UPDATE ON album_external_identity WHEN NEW.provider='spotify' BEGIN
 DELETE FROM track_provider_exclusion WHERE provider='spotify' AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id=NEW.album_id) AND EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=track_provider_exclusion.track_id);
END;
CREATE TRIGGER lifecycle_manual_track_association_removed AFTER DELETE ON manual_track_association WHEN OLD.album_provider='spotify' BEGIN
 UPDATE spotify_connection_review SET stale=1 WHERE track_id=OLD.track_id AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=OLD.track_id);
END;
CREATE TRIGGER lifecycle_provider_track_association_removed AFTER DELETE ON provider_track_association WHEN OLD.album_provider='spotify' BEGIN
 UPDATE spotify_connection_review SET stale=1 WHERE track_id=OLD.track_id AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=OLD.track_id);
END;
CREATE TRIGGER lifecycle_recording_identity_insert AFTER INSERT ON recording_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.recording_id=NEW.recording_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_recording_identity_update AFTER UPDATE ON recording_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.recording_id=OLD.recording_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.recording_id=NEW.recording_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
CREATE TRIGGER lifecycle_recording_identity_delete AFTER DELETE ON recording_external_identity BEGIN
UPDATE spotify_connection_review SET stale=1 WHERE stale=0 AND track_id IN(SELECT t.id FROM track t JOIN release r ON r.id=t.release_id WHERE r.album_id IN(SELECT r2.album_id FROM track t2 JOIN release r2 ON r2.id=t2.release_id WHERE t2.recording_id=OLD.recording_id)) AND NOT EXISTS(SELECT 1 FROM trusted_spotify_track s WHERE s.track_id=spotify_connection_review.track_id) AND NOT EXISTS(SELECT 1 FROM track_provider_exclusion x WHERE x.track_id=spotify_connection_review.track_id AND x.provider='spotify');
END;
PRAGMA user_version=29;
COMMIT;
