DROP TRIGGER IF EXISTS lifecycle_recording_identity_insert;
DROP TRIGGER IF EXISTS lifecycle_recording_identity_update;
DROP TRIGGER IF EXISTS lifecycle_recording_identity_delete;
DROP TRIGGER IF EXISTS spotify_exclusion_update_unconnected;
DROP TRIGGER IF EXISTS lifecycle_exclusion_added;
DROP TRIGGER IF EXISTS lifecycle_exclusion_removed;
DROP TRIGGER IF EXISTS lifecycle_album_identity_connected_insert;
DROP TRIGGER IF EXISTS lifecycle_album_identity_connected_update;
DROP TRIGGER IF EXISTS lifecycle_manual_track_association_removed;
DROP TRIGGER IF EXISTS lifecycle_provider_track_association_removed;
DROP TRIGGER IF EXISTS spotify_exclusion_unconnected;
DROP TRIGGER IF EXISTS lifecycle_track_provider_evidence_insert;
DROP TRIGGER IF EXISTS lifecycle_track_provider_evidence_update;
DROP TRIGGER IF EXISTS lifecycle_track_provider_evidence_delete;
DROP TRIGGER IF EXISTS lifecycle_track_application_metadata_insert;
DROP TRIGGER IF EXISTS lifecycle_track_application_metadata_update;
DROP TRIGGER IF EXISTS lifecycle_track_application_metadata_delete;
DROP TRIGGER IF EXISTS lifecycle_track_title_override_insert;
DROP TRIGGER IF EXISTS lifecycle_track_title_override_update;
DROP TRIGGER IF EXISTS lifecycle_track_title_override_delete;
DROP TRIGGER IF EXISTS lifecycle_track_external_identity_insert;
DROP TRIGGER IF EXISTS lifecycle_track_external_identity_update;
DROP TRIGGER IF EXISTS lifecycle_track_external_identity_delete;
DROP TRIGGER IF EXISTS lifecycle_track_artist_credit_insert;
DROP TRIGGER IF EXISTS lifecycle_track_artist_credit_update;
DROP TRIGGER IF EXISTS lifecycle_track_artist_credit_delete;
DROP TRIGGER IF EXISTS lifecycle_track_duration_observation_insert;
DROP TRIGGER IF EXISTS lifecycle_track_duration_observation_update;
DROP TRIGGER IF EXISTS lifecycle_track_duration_observation_delete;
DROP TRIGGER IF EXISTS lifecycle_track_source_insert;
DROP TRIGGER IF EXISTS lifecycle_track_source_update;
DROP TRIGGER IF EXISTS lifecycle_track_source_delete;
DROP TRIGGER IF EXISTS lifecycle_album_provider_evidence_insert;
DROP TRIGGER IF EXISTS lifecycle_album_provider_evidence_update;
DROP TRIGGER IF EXISTS lifecycle_album_provider_evidence_delete;
DROP TRIGGER IF EXISTS lifecycle_album_application_metadata_insert;
DROP TRIGGER IF EXISTS lifecycle_album_application_metadata_update;
DROP TRIGGER IF EXISTS lifecycle_album_application_metadata_delete;
DROP TRIGGER IF EXISTS lifecycle_album_external_identity_insert;
DROP TRIGGER IF EXISTS lifecycle_album_external_identity_update;
DROP TRIGGER IF EXISTS lifecycle_album_external_identity_delete;
DROP TRIGGER IF EXISTS lifecycle_album_artist_credit_insert;
DROP TRIGGER IF EXISTS lifecycle_album_artist_credit_update;
DROP TRIGGER IF EXISTS lifecycle_album_artist_credit_delete;
DROP TRIGGER IF EXISTS lifecycle_release_external_identity_insert;
DROP TRIGGER IF EXISTS lifecycle_release_external_identity_update;
DROP TRIGGER IF EXISTS lifecycle_release_external_identity_delete;
DROP TRIGGER IF EXISTS lifecycle_release_artist_credit_insert;
DROP TRIGGER IF EXISTS lifecycle_release_artist_credit_update;
DROP TRIGGER IF EXISTS lifecycle_release_artist_credit_delete;
DROP TRIGGER IF EXISTS lifecycle_file_metadata_observation_insert;
DROP TRIGGER IF EXISTS lifecycle_file_metadata_observation_update;
DROP TRIGGER IF EXISTS lifecycle_file_metadata_observation_delete;
DROP TRIGGER IF EXISTS lifecycle_file_artist_observation_insert;
DROP TRIGGER IF EXISTS lifecycle_file_artist_observation_update;
DROP TRIGGER IF EXISTS lifecycle_file_artist_observation_delete;
DROP TRIGGER IF EXISTS lifecycle_artist_insert;
DROP TRIGGER IF EXISTS lifecycle_artist_update;
DROP TRIGGER IF EXISTS lifecycle_artist_delete;
DROP TRIGGER IF EXISTS lifecycle_artist_external_identity_insert;
DROP TRIGGER IF EXISTS lifecycle_artist_external_identity_update;
DROP TRIGGER IF EXISTS lifecycle_artist_external_identity_delete;
DROP TRIGGER IF EXISTS lifecycle_artist_equivalence_insert;
DROP TRIGGER IF EXISTS lifecycle_artist_equivalence_update;
DROP TRIGGER IF EXISTS lifecycle_artist_equivalence_delete;
DROP TRIGGER IF EXISTS lifecycle_track_insert;
DROP TRIGGER IF EXISTS lifecycle_track_update;
DROP TRIGGER IF EXISTS lifecycle_track_delete;
DROP TRIGGER IF EXISTS lifecycle_release_relationship;
DROP TRIGGER IF EXISTS lifecycle_connected_track_external_identity_insert;
DROP TRIGGER IF EXISTS lifecycle_connected_track_external_identity_update;
DROP TRIGGER IF EXISTS lifecycle_connected_manual_track_association_insert;
DROP TRIGGER IF EXISTS lifecycle_connected_manual_track_association_update;
DROP TRIGGER IF EXISTS lifecycle_connected_provider_track_association_insert;
DROP TRIGGER IF EXISTS lifecycle_connected_provider_track_association_update;
DROP TABLE IF EXISTS spotify_program_cache;
DROP TABLE IF EXISTS spotify_reconciliation_cache;
DROP TABLE IF EXISTS track_provider_exclusion;
DROP TABLE IF EXISTS track_provider_evidence;
DROP TABLE IF EXISTS album_provider_evidence;
DROP TABLE IF EXISTS artist_equivalence;
DROP INDEX IF EXISTS spotify_review_manual;
DROP INDEX IF EXISTS spotify_review_automatic;
DROP VIEW IF EXISTS trusted_spotify_track;
DROP TRIGGER IF EXISTS spotify_review_track_added;
DROP TABLE IF EXISTS spotify_connection_review;
DROP TABLE track_duration_observation;
DROP INDEX song_details_artist;
DROP INDEX song_details_album;
DROP INDEX song_details_genre;
ALTER TABLE effective_track_metadata DROP COLUMN duration_approximate;
ALTER TABLE effective_track_metadata DROP COLUMN genre_names;
DROP TABLE IF EXISTS playlist_source; DROP TABLE IF EXISTS playlist_entry;
DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS file_genre_observation;
ALTER TABLE file_metadata_observation DROP COLUMN genres_observed;
DROP TABLE IF EXISTS local_root_source;
DROP TABLE IF EXISTS local_source_suppression;
DROP TRIGGER IF EXISTS album_order_release_application_metadata_delete;
DROP TRIGGER IF EXISTS album_order_release_application_metadata_update;
DROP TRIGGER IF EXISTS album_order_release_application_metadata_insert;
DROP TRIGGER IF EXISTS album_order_effective_track_metadata_delete;
DROP TRIGGER IF EXISTS album_order_effective_track_metadata_update;
DROP TRIGGER IF EXISTS album_order_effective_track_metadata_insert;
DROP TRIGGER IF EXISTS album_order_metadata_insert;
DROP TRIGGER IF EXISTS album_order_metadata_update;
DROP TRIGGER IF EXISTS album_order_credit_insert;
DROP TRIGGER IF EXISTS album_order_credit_update;
DROP TRIGGER IF EXISTS album_order_credit_delete;
DROP TRIGGER IF EXISTS album_order_artist_name;
DROP TRIGGER IF EXISTS artwork_album_external_identity_insert;
DROP TRIGGER IF EXISTS artwork_album_external_identity_delete;
DROP TRIGGER IF EXISTS artwork_library_membership_insert;
DROP TRIGGER IF EXISTS artwork_library_membership_delete;
DROP TRIGGER IF EXISTS artwork_track_source_insert;
DROP TRIGGER IF EXISTS artwork_track_source_delete;
DROP TRIGGER IF EXISTS artwork_local_change;
DROP TABLE IF EXISTS album_browse_order;
DROP TABLE IF EXISTS album_artwork;
DROP INDEX IF EXISTS album_browse_year;

DROP TRIGGER IF EXISTS artist_lookup_insert;
DROP TRIGGER IF EXISTS artist_lookup_update;
DROP TRIGGER IF EXISTS artist_lookup_delete;
DROP TRIGGER IF EXISTS album_lookup_insert;
DROP TRIGGER IF EXISTS album_lookup_update;
DROP TRIGGER IF EXISTS album_lookup_delete;
DROP TABLE IF EXISTS artist_lookup;
DROP TABLE IF EXISTS album_lookup;
DROP TABLE IF EXISTS output_calibration;
DROP TRIGGER recording_manual_confirmation;
DROP TRIGGER manual_recording_claim_removed;
DROP TABLE manual_track_recording_claim;
DROP TABLE recording_manual_identity;
DROP TABLE manual_track_association;
DROP TABLE IF EXISTS provider_track_association;

-- Downgrade fixtures also remove the later library browsing indexes.
DROP INDEX IF EXISTS artist_browse_name;
DROP INDEX IF EXISTS album_browse_title;
DROP INDEX IF EXISTS track_browse_title;

DROP TABLE IF EXISTS local_artist_context;
